### ISSUE TITLE
Unable to load the ckpt file

### ISSUE THREAD

**Issue by vikashg** [lab-midas/autoPET#12]
Hi, 
When I am trying to run the prediction. I am getting the following error
```
Start prediction
starting
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/algorithm/process.py", line 90, in <module>
    Unet_baseline().process()
  File "/opt/algorithm/process.py", line 84, in process
    monai_unet.run_inference(self.ckpt_path, self.nii_path, self.output_path)
  File "/opt/algorithm/monai_unet.py", line 137, in run_inference
    segment_PETCT(ckpt_path, data_dir, export_dir)
  File "/opt/algorithm/monai_unet.py", line 108, in segment_PETCT
    net = Net.load_from_checkpoint(ckpt_path)
  File "/home/algorithm/.local/lib/python3.10/site-packages/pytorch_lightning/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/home/algorithm/.local/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1586, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/algorithm/.local/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/home/algorithm/.local/lib/python3.10/site-packages/lightning_fabric/utilities/cloud_io.py", line 57, in _load
    return torch.load(f, map_location=map_location)  # type: ignore[arg-type]
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

After googling a bit I found that the it might be caused because the model `epoch=777-step=64573.ckpt` is not downloaded properly. After checking the size I found the model size was 4.0k
Can you please look into this.

**Comment by thomaskuestner** [comment]
Did you check out the GIT repository with GIT LFS? 
`git lfs pull`
The trained weights are stored as LFS.

**Comment by vikashg** [comment]
Thanks that works.
